language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: q0swH7PPhZyIpZWLWCQ6TpeCHqoHu1Tfov3i14owHYENbO0Jm6jljC+P6jMwhhcHcD5RwcDe50VGo5L5xFyf//QEP+WORn1Xqgyh/fCdWf9fJpQnrx77eJ8howyzM3+Il/XvMXmcBNJuLZrC8g8V90LWmI8abhgWGyoiGrUSXgootYGKN4qFlc5vEBu49xiiXcpvNZbDO39McFq7MtN22J/89tcqGWvRZippF2F6/grxvxY+X1FUSOQvc4CxlMsfSy7RDKr6cWuR6Hw9pHJgDmU3Dbrr/ShFGz4hS458YqrDcyCglSvjyb0Vju/gTCWShFosOY1l9m+OqWGlQI7nK7FOHzBBe1I6uOTs+Zv4zr0x6ztNuhk0OSreu/vSnS6Mxue7so9Tt7+Xf2BT1MKgxXK6ROSrFhbgBNLthPUJ0Q1aFq62L4Y4WgOIzapfELPDLv7F4jYJRdHiamJuXqSS5nSu89zO4ktt1IREy0vdlhC00TZ20TyJ4ZZjs4ksx7Cx0EezZsZFwc7Oj77DIBmr6QcEyMb1trl2feKAf9sPvuAnLM1IfY31phcLaxw23EDRj6IKHdm5wktSksy5MvOdpUIqpERtnIDwPiJKukuC9XZJHCN1NILMmiqOCTHDiyiPC1TmFfqi9wNKJKXxJiTQHFkSusqxZqmuwUbPLU8YGEA=
  app: desolate-hamlet-89765
  on:
    branch: master
    python: '3.4'
    repo: mbreisch/real-python-flasktaskr
